A, TRANSPOSE

NUMPY CODE

In [ ]:
import numpy as np

#Tao array 2d
arr_1 = np.array([[1, 2], [3, 4]])

#Chuyen vi array
#Cach 1: su dung ham np.transpose()
arr_transposed_1 = np.transpose(arr_1)
print(arr_transposed_1)

[[1 3]
 [2 4]]


In [ ]:
#Cach 2: su hang toan tu T
arr_transposed_2 = arr_1.T
print(arr_transposed_2)

[[1 3]
 [2 4]]


TORCH CODE

In [ ]:
import torch

In [ ]:
#Tao tensor 2d
tensor_1 = torch.tensor([[1, 2], [3, 4]])
#Chuyen vi tensor
#Cach 1: su dung ham torch.t()
tensor_transposed_1 = torch.t(tensor_1)
print(tensor_transposed_1)

tensor([[1, 3],
        [2, 4]])


In [ ]:
#Cach 2: su dung ham torch.transpose()
tensor_transposed_2 = torch.transpose(tensor_1, 0, 1)
print(tensor_transposed_2)

tensor([[1, 3],
        [2, 4]])


TENSOR FLOW CODE

In [ ]:
import tensorflow as tf

#Tao tensor 2d
tensor_1 = tf.constant([[1, 2],  [3, 4]])

#Chuyen vi tensor
tensor_transposed = tf.transpose(tensor_1)
print("tensor 1: \n", tensor_1)
print("tensor 1 sau khi chuyen vi: \n", tensor_transposed)

tensor 1: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor 1 sau khi chuyen vi: 
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


B, SUMMATION:

NUMPY

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
#tinh tong tat ca phan tu
total_sum = np.sum(arr)

#tinh tong theo cot (theo chieu doc)
col_sum = np.sum(arr, axis = 0)

#tinh tong theo hang (theo chieu ngang)
row_sum = np.sum(arr, axis = 1)

print("Tong tat ca: ", total_sum)
print("Tong theo cot: \n", col_sum)
print("Tong theo hang: \n", row_sum)

Tong tat ca:  21
Tong theo cot: 
 [5 7 9]
Tong theo hang: 
 [ 6 15]


In [ ]:
#trong torch: torch.sum(tensor_1, axis = 0)
#trong tensorflow: tf.reduce_sum(tensor_1, axis = 1)

In [ ]:
np.random.seed(2024)
np_array_1 = np.random.randint(-10, 10, size = (3, 4))
np_array_2 = np.random.randint(-10, 10, size = (3, 4))
np_array_2_transposed = np.transpose(np_array_2)

print(np.matmul(np_array_1, np_array_2_transposed))

[[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]


In [ ]:
tf_tensor1 = tf.random.uniform((3, 4), -10, 10, dtype = tf.dtypes.int32, seed = 2024)
tf_tensor2 = tf.random.uniform((3, 4), -10, 10, dtype = tf.dtypes.int32, seed = 2024)
tf_tensor2_T = tf.transpose(tf_tensor2)

print(tf.linalg.matmul(tf_tensor1, tf_tensor2_T))

tf.Tensor(
[[  18  -28   82]
 [ -24  -72 -111]
 [  62    4   46]], shape=(3, 3), dtype=int32)


In [ ]:
torch.manual_seed(2024)

torch_1 = torch.randint(-10, 10, size=(3,4), dtype = torch.int32)
torch_2 = torch.randint(-10, 10, size=(3,4), dtype = torch.int32)
torch_2_T = torch.transpose(torch_2, 0, 1)

print(torch.matmul(torch_1, torch_2_T))

tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]], dtype=torch.int32)
